# Generated by Django 4.2.14 on 2024-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginform',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registerform',
            fields=[
                ('reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=65)),
                ('lastname', models.CharField(max_length=65)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='pics/')),
                ('user_type', models.CharField(choices=[('company', 'Company'), ('applicant', 'Applicant')], max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
