# Generated by Django 4.2.14 on 2024-07-18 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('budget', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
