# Generated by Django 4.2.14 on 2024-07-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vacancy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='project',
        ),
    ]
