# Generated by Django 4.2.14 on 2024-07-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_vacancy_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
