# Generated by Django 4.2.14 on 2024-07-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_project_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(choices=[('company', 'Company'), ('applicant', 'Applicant')], on_delete=django.db.models.deletion.CASCADE, to='myapp.usertype'),
        ),
    ]
