# Generated by Django 4.2.14 on 2024-07-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usertype_remove_user_resume_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('applicant', 'Applicant')], max_length=10),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
