# Generated by Django 4.2.14 on 2024-07-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_apply_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(default='company_name', max_length=100),
            preserve_default=False,
        ),
    ]
