# Generated by Django 4.2.14 on 2024-07-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_project',
            old_name='attachment',
            new_name='attachments',
        ),
    ]
