# Generated by Django 4.2.14 on 2024-07-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_attachment_apply_project_attachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginform',
        ),
        migrations.DeleteModel(
            name='Registerform',
        ),
    ]
